#!/bin/sh
set -e

PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-128M}
PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-146M}
PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-30}

{
  echo "memory_limit = $PHP_MEMORY_LIMIT"
  echo "upload_max_filesize = $PHP_UPLOAD_MAX_FILESIZE"
  echo "post_max_size = $PHP_POST_MAX_SIZE"
  echo "max_execution_time = $PHP_MAX_EXECUTION_TIME"
} > "$PHP_INI_DIR/app.conf.d/60_docker_env.ini"

if [ "$1" = 'frankenphp' ] || [ "$1" = 'php' ] || [ "$1" = 'bin/console' ]; then

	if [ "${DUMP_COMPOSER_ENV:-0}" = "1" ]; then
		echo 'Dumping env for composer'
		composer dump-env prod
	fi

	bin/console cache:clear

	if [ -n "${DATABASE_URL:-}" ] && [ "${RUN_DOCTRINE_MIGRATIONS:-0}" = "1" ]; then
		echo 'Waiting for database to be ready...'
		ATTEMPTS_LEFT_TO_REACH_DATABASE=60
		until [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ] || DATABASE_ERROR=$(php bin/console dbal:run-sql -q "SELECT 1" 2>&1); do
			if [ $? -eq 255 ]; then
				ATTEMPTS_LEFT_TO_REACH_DATABASE=0
				break
			fi
			sleep 1
			ATTEMPTS_LEFT_TO_REACH_DATABASE=$((ATTEMPTS_LEFT_TO_REACH_DATABASE - 1))
			echo "Still waiting for database... $ATTEMPTS_LEFT_TO_REACH_DATABASE attempts left."
		done

		if [ $ATTEMPTS_LEFT_TO_REACH_DATABASE -eq 0 ]; then
			echo 'The database is not up or not reachable:'
			echo "$DATABASE_ERROR"
			exit 1
		else
			echo 'The database is now ready and reachable'
		fi

		if [ "$(find ./migrations -iname '*.php' -print -quit)" ]; then
			php bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing
		fi
	fi

	echo 'PHP app ready!'
fi

sync

exec docker-php-entrypoint "$@"
