name: Publish Docker image

on: push

jobs:
    build-and-publish-image:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Resolve branch name
                id: vars
                run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
            -
                name: Build and push common
                uses: docker/build-push-action@v2
                with:
                    file: ./common.Dockerfile
                    push: true
                    tags: dontdrinkandroot/php:${{ steps.vars.outputs.short_ref }}-common
            -
                name: Build and push test
                uses: docker/build-push-action@v2
                with:
                    file: ./test.Dockerfile
                    push: true
                    tags: dontdrinkandroot/php:${{ steps.vars.outputs.short_ref }}-test
                    build-args: |
                        FROM=dontdrinkandroot/php:${{ steps.vars.outputs.short_ref }}-common
            -
                name: Build and push dev
                uses: docker/build-push-action@v2
                with:
                    file: ./dev.Dockerfile
                    push: true
                    tags: dontdrinkandroot/php:${{ steps.vars.outputs.short_ref }}-dev
                    build-args: |
                        FROM=dontdrinkandroot/php:${{ steps.vars.outputs.short_ref }}-test
